"""add multi-currency fields

Revision ID: 02cf38a5b6f8
Revises: b9789195f590
Create Date: 2026-08-06 22:04:09.132346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02cf38a5b6f8'
down_revision = 'b9789195f590'
branch_labels = None
depends_on = None


def upgrade():
    # NOT: Alembic autogenerate, onceki migration'da op.execute() ile elle
    # eklenen pg_trgm/GIN indexlerini (model metadata'da izlenmedigi icin)
    # "kaldirilmis" saniyordu - bu 4 drop_index cagrisi kasitli olarak
    # SILINDI, o indexler kalmaya devam etmeli.
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deal', schema=None) as batch_op:
        # server_default: mevcut 48 satirin hepsi TRY kabul edilir (coklu
        # para birimi oncesi teklifler zaten TL cinsindendi) - NOT NULL
        # kisitina uymalari icin gerekli, Python-tarafi default (='TRY')
        # sadece YENI satirlar icin gecerli, mevcutlari doldurmaz.
        batch_op.add_column(sa.Column('para_birimi', sa.String(length=3), nullable=False, server_default='TRY'))
        batch_op.add_column(sa.Column('kullanilan_kur', sa.Float(), nullable=True))

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kur_orani', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('kur_orani')

    with op.batch_alter_table('deal', schema=None) as batch_op:
        batch_op.drop_column('kullanilan_kur')
        batch_op.drop_column('para_birimi')

    # ### end Alembic commands ###
