"""add_deal_payment_terms

Revision ID: 0b2adfa139d6
Revises: 0d1d767e7447
Create Date: 2026-07-28 02:04:18.886181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b2adfa139d6'
down_revision = '0d1d767e7447'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vade_gun', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('pesinat', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bakiye_odemesi', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deal', schema=None) as batch_op:
        batch_op.drop_column('bakiye_odemesi')
        batch_op.drop_column('pesinat')
        batch_op.drop_column('vade_gun')

    # ### end Alembic commands ###
