"""add performance indexes

Revision ID: 0ce9738d82b8
Revises: 9cbc8a78864b
Create Date: 2026-08-05 00:01:39.626324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ce9738d82b8'
down_revision = '9cbc8a78864b'
branch_labels = None
depends_on = None


def upgrade():
    # Musteri arama kutusu (customers() route) '%q%' bicimindeki ILIKE
    # sorgular kullaniyor - normal btree index bunlara yardimci olmaz
    # (bastaki '%' index taramasini engeller). pg_trgm/GIN trigram index
    # bu tur "contains" aramalarini hizlandirir.
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm')
    op.execute("CREATE INDEX ix_customer_first_name_trgm ON customer USING gin (first_name gin_trgm_ops)")
    op.execute("CREATE INDEX ix_customer_last_name_trgm ON customer USING gin (last_name gin_trgm_ops)")
    op.execute("CREATE INDEX ix_customer_company_name_trgm ON customer USING gin (company_name gin_trgm_ops)")
    op.execute("CREATE INDEX ix_customer_phone_trgm ON customer USING gin (phone gin_trgm_ops)")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_status'), ['status'], unique=False)

    with op.batch_alter_table('customer_statement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_statement_customer_id'), ['customer_id'], unique=False)

    with op.batch_alter_table('customer_visit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_visit_customer_id'), ['customer_id'], unique=False)

    with op.batch_alter_table('daily_report', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_report_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_report_report_date'), ['report_date'], unique=False)

    with op.batch_alter_table('deal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deal_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deal_stage'), ['stage'], unique=False)

    with op.batch_alter_table('deal_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deal_item_deal_id'), ['deal_id'], unique=False)

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_deal_id'), ['deal_id'], unique=False)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_deal_id'), ['deal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_status'), ['status'], unique=False)

    with op.batch_alter_table('production', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_production_status'), ['status'], unique=False)

    with op.batch_alter_table('production_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_production_item_production_id'), ['production_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_item_production_id'))

    with op.batch_alter_table('production', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_status'))

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_status'))
        batch_op.drop_index(batch_op.f('ix_payment_deal_id'))
        batch_op.drop_index(batch_op.f('ix_payment_customer_id'))

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_deal_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_customer_id'))

    with op.batch_alter_table('deal_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deal_item_deal_id'))

    with op.batch_alter_table('deal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deal_stage'))
        batch_op.drop_index(batch_op.f('ix_deal_customer_id'))

    with op.batch_alter_table('daily_report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_report_report_date'))
        batch_op.drop_index(batch_op.f('ix_daily_report_customer_id'))

    with op.batch_alter_table('customer_visit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_visit_customer_id'))

    with op.batch_alter_table('customer_statement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_statement_customer_id'))

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_status'))
        batch_op.drop_index(batch_op.f('ix_customer_phone'))

    # ### end Alembic commands ###

    op.execute("DROP INDEX IF EXISTS ix_customer_phone_trgm")
    op.execute("DROP INDEX IF EXISTS ix_customer_company_name_trgm")
    op.execute("DROP INDEX IF EXISTS ix_customer_last_name_trgm")
    op.execute("DROP INDEX IF EXISTS ix_customer_first_name_trgm")
    # pg_trgm extension'ini kaldirmiyoruz - baska bir seyin ona bagimli
    # olma ihtimaline karsi guvenli tarafta kaliyoruz.
