"""add deal payment schedule fields (pesinat_orani, pesinat_tarihi, bakiye_tarihi)

Revision ID: 1c2f57d3edad
Revises: 643f7b446062
Create Date: 2026-07-31 23:58:43.193830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c2f57d3edad'
down_revision = '643f7b446062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pesinat_orani', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pesinat_tarihi', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('bakiye_tarihi', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deal', schema=None) as batch_op:
        batch_op.drop_column('bakiye_tarihi')
        batch_op.drop_column('pesinat_tarihi')
        batch_op.drop_column('pesinat_orani')

    # ### end Alembic commands ###
