"""Add status to DailyReport

Revision ID: 290123af7c0c
Revises: 401d66fa0fac
Create Date: 2026-07-06 00:22:14.425089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '290123af7c0c'
down_revision = '401d66fa0fac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_report', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
