"""widen deal_item boy en fields

Revision ID: 38e262d9d80a
Revises: 02cf38a5b6f8
Create Date: 2026-08-07 00:43:52.213150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38e262d9d80a'
down_revision = '02cf38a5b6f8'
branch_labels = None
depends_on = None


def upgrade():
    # NOT: Alembic autogenerate, onceki migration'da op.execute() ile elle
    # eklenen pg_trgm/GIN indexlerini (model metadata'da izlenmedigi icin)
    # "kaldirilmis" saniyordu - bu 4 drop_index cagrisi kasitli olarak
    # SILINDI, o indexler kalmaya devam etmeli.
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deal_item', schema=None) as batch_op:
        batch_op.alter_column('boy',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('en',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deal_item', schema=None) as batch_op:
        batch_op.alter_column('en',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('boy',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###
