"""add customer musteri_no field

Revision ID: 3c2f947f44d6
Revises: a8af268e06e7
Create Date: 2026-08-01 01:06:23.155198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c2f947f44d6'
down_revision = 'a8af268e06e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('musteri_no', sa.String(length=10), nullable=True))
        batch_op.create_unique_constraint(None, ['musteri_no'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('musteri_no')

    # ### end Alembic commands ###
