"""add manual_rate to commission

Revision ID: 401d66fa0fac
Revises: 26f4a7b5a6d2
Create Date: 2026-07-04 10:41:13.666508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '401d66fa0fac'
down_revision = '26f4a7b5a6d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manual_rate', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commission', schema=None) as batch_op:
        batch_op.drop_column('manual_rate')

    # ### end Alembic commands ###
