"""add_production_item_specs_and_shipment_faturasiz_cikis

Revision ID: 5b0397d38754
Revises: ad1aab736982
Create Date: 2026-07-15 00:04:03.559104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b0397d38754'
down_revision = 'ad1aab736982'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('olcu', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('baski_bilgisi', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('kagit_tipi', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('gramaj', sa.String(length=50), nullable=True))

    with op.batch_alter_table('shipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('faturasiz_cikis', sa.Boolean(), nullable=False, server_default=sa.false()))
    with op.batch_alter_table('shipment', schema=None) as batch_op:
        batch_op.alter_column('faturasiz_cikis', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment', schema=None) as batch_op:
        batch_op.drop_column('faturasiz_cikis')

    with op.batch_alter_table('production_item', schema=None) as batch_op:
        batch_op.drop_column('gramaj')
        batch_op.drop_column('kagit_tipi')
        batch_op.drop_column('baski_bilgisi')
        batch_op.drop_column('olcu')

    # ### end Alembic commands ###
