"""add_estimated_and_actual_delivery_date_to_shipment

Revision ID: 6460f295f74b
Revises: 332857de1e8d
Create Date: 2026-07-13 00:00:43.583916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6460f295f74b'
down_revision = '332857de1e8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimated_delivery_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('actual_delivery_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment', schema=None) as batch_op:
        batch_op.drop_column('actual_delivery_date')
        batch_op.drop_column('estimated_delivery_date')

    # ### end Alembic commands ###
