"""add_payment_deal_id_and_statement_payment_id

Revision ID: 7c1d4e9a2f3b
Revises: 3ad2d9921869
Create Date: 2026-07-29 23:10:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c1d4e9a2f3b'
down_revision = '3ad2d9921869'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deal_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_payment_deal_id', 'deal', ['deal_id'], ['id'])

    with op.batch_alter_table('customer_statement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_customer_statement_payment_id', 'payment', ['payment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_statement', schema=None) as batch_op:
        batch_op.drop_constraint('fk_customer_statement_payment_id', type_='foreignkey')
        batch_op.drop_column('payment_id')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_payment_deal_id', type_='foreignkey')
        batch_op.drop_column('deal_id')

    # ### end Alembic commands ###
