"""add_tasarim_gorseli_fields

Revision ID: 8e65c86174f0
Revises: 0b2adfa139d6
Create Date: 2026-07-28 02:07:38.456348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e65c86174f0'
down_revision = '0b2adfa139d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tasarim_gorseli', sa.String(length=300), nullable=True))

    with op.batch_alter_table('production', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tasarim_gorseli_override', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production', schema=None) as batch_op:
        batch_op.drop_column('tasarim_gorseli_override')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('tasarim_gorseli')

    # ### end Alembic commands ###
