"""add siparis dongusu gun to customer

Revision ID: 9a71f422a37c
Revises: d3e8b1f42a90
Create Date: 2026-07-08 23:28:53.883311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a71f422a37c'
down_revision = 'd3e8b1f42a90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('siparis_dongusu_gun', sa.Integer(), nullable=False, server_default='120'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('siparis_dongusu_gun')

    # ### end Alembic commands ###
