"""add urun field to manual_planning_entry

Revision ID: 9cbc8a78864b
Revises: 9f2a4e7c1d3b
Create Date: 2026-08-04 01:10:23.619147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cbc8a78864b'
down_revision = '9f2a4e7c1d3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manual_planning_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('urun', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manual_planning_entry', schema=None) as batch_op:
        batch_op.drop_column('urun')

    # ### end Alembic commands ###
