"""add customerstatement source field for pdf import

Revision ID: a8af268e06e7
Revises: 1c2f57d3edad
Create Date: 2026-08-01 00:55:41.203502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8af268e06e7'
down_revision = '1c2f57d3edad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_statement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=20), nullable=False, server_default='manuel'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_statement', schema=None) as batch_op:
        batch_op.drop_column('source')

    # ### end Alembic commands ###
