"""add deal item paper spec fields

Revision ID: b9789195f590
Revises: 0ce9738d82b8
Create Date: 2026-08-05 00:24:19.571921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9789195f590'
down_revision = '0ce9738d82b8'
branch_labels = None
depends_on = None


def upgrade():
    # NOT: Alembic autogenerate, migration 0ce9738d82b8'de op.execute() ile
    # elle eklenen pg_trgm/GIN indexlerini (model metadata'da izlenmedigi
    # icin) "kaldirilmis" saniyordu - bu 4 drop_index cagrisi kasitli olarak
    # SILINDI, o indexler kalmaya devam etmeli.
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deal_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kagit_cinsi', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('boy', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('en', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('renk', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('teslim_tarihi', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deal_item', schema=None) as batch_op:
        batch_op.drop_column('teslim_tarihi')
        batch_op.drop_column('renk')
        batch_op.drop_column('en')
        batch_op.drop_column('boy')
        batch_op.drop_column('kagit_cinsi')

    # ### end Alembic commands ###
