"""add urun_tipi, ticaret_durumu, taban_olcusu fields

Revision ID: cbb6cab15b80
Revises: 3c2f947f44d6
Create Date: 2026-08-01 01:18:23.541508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbb6cab15b80'
down_revision = '3c2f947f44d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deal_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('urun_tipi', sa.String(length=20), nullable=False, server_default='uretim'))

    with op.batch_alter_table('production_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('urun_tipi', sa.String(length=20), nullable=False, server_default='uretim'))
        batch_op.add_column(sa.Column('ticaret_durumu', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('taban_olcusu', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_item', schema=None) as batch_op:
        batch_op.drop_column('taban_olcusu')
        batch_op.drop_column('ticaret_durumu')
        batch_op.drop_column('urun_tipi')

    with op.batch_alter_table('deal_item', schema=None) as batch_op:
        batch_op.drop_column('urun_tipi')

    # ### end Alembic commands ###
